import uuid
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from backend.db.session import get_db
from backend.models.ticket import Ticket
from backend.models.schemas import SuggestRequest, SuggestResponse

router = APIRouter(prefix="/suggest", tags=["Suggest"])


@router.post("", response_model=SuggestResponse)
def suggest_reply(request: SuggestRequest, db: Session = Depends(get_db)):
    """
    Generate a suggested agent reply for a given support ticket message.
    Uses Gemini to produce a professional, empathetic response and also provide guidence or solution to the problem .
    """
    try:
        from backend.pipeline.responder import generate_suggested_reply
    except ImportError as e:
        raise HTTPException(status_code=503, detail=f"Suggest service unavailable: {e}")

    # If ticket_id is given, enrich context with stored category
    category = request.category
    if request.ticket_id and not category:
        ticket = db.query(Ticket).filter(Ticket.ticket_id == request.ticket_id).first()
        if ticket:
            category = ticket.category

    result = generate_suggested_reply(message=request.message, category=category)

    # Persist the suggestion back to the ticket if ticket_id was given
    if request.ticket_id:
        ticket = db.query(Ticket).filter(Ticket.ticket_id == request.ticket_id).first()
        if ticket and not ticket.suggested_reply:
            ticket.suggested_reply = result["reply"]
            db.commit()

    return SuggestResponse(
        suggested_reply=result["reply"],
        category=category,
        confidence_note=result.get("note", "Generated by Gemini 2.0 Flash"),
    )
